name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BEAT_VERSION: v0.0.1 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        wget "https://github.com/seungyongshim/nvidiagpubeat/releases/download/${BEAT_VERSION}/nvidiagpubeat"
        docker build . -t mirerosystemkr/my-image-name:${GITHUB_SHA::8}
        
