name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BEAT_VERSION: v0.0.1 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        wget "https://github.com/seungyongshim/nvidiagpubeat/releases/download/${BEAT_VERSION}/nvidiagpubeat"
        docker login -u ${{ secrets.DOCKER_HUB_ID }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build . -t mirerosystemkr/nvidiagpubeat:${GITHUB_SHA::8}
        docker push mirerosystemkr/nvidiagpubeat:${GITHUB_SHA::8}
        
